rm(list=ls())
setwd("D:/Archivos de clases/Universidad/V Semestre/AED/Hackaton/Reto1/src")

library('readr')
library('FactoClass')
library('FactoMineR')
library('ade4')
library('dplyr')
library('ggplot2')
library('aplpack')
library('plotly')
library('lmtest')
